name: adhan_dart
version: 1.1.1
description: >-
    Library to calculate prayer times for muslims.
    Based on precise astronomical formula.
homepage: https://github.com/prayer-timetable/adhan_dart/
documentation: https://github.com/prayer-timetable/adhan_dart/
environment:
    sdk: '>=2.12.0 <4.0.0'
dependencies:

dev_dependencies:
    timezone: ^0.9.3
    flutter_lints: ^4.0.0
