name: adhan_dart
version: 1.0.2
description: >-
  Library to calculate prayer times for muslims.
  Based on precise astronomical formula.
homepage: https://github.com/prayer-timetable/adhan_dart/
documentation: https://github.com/prayer-timetable/adhan_dart/
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:

dev_dependencies:
  timezone: ^0.6.1
