name: adhan
version: 1.0.0
description: >-
  Library to calculate prayer times for muslims.
  Based on precise astronomical formula.
homepage: https://github.com/prayer-timetable/adhan_dart/
documentation: https://github.com/prayer-timetable/adhan_dart/
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  timezone: ^0.5.7

dev_dependencies:
